### ISSUE TITLE
Error: Callback must be a function

### ISSUE THREAD

**Issue by wind13** [ant-design/intl-example#16]
测试了一下报了如下的错：

```
➜  intl-example git:(master) ✗ npm run dev

> antd-intl-example@1.0.0 dev /Users/samliu/gits/demos/intl-example
> dora -p 8001 --plugins webpack,proxy,hmr,livereload

(node:39378) [DEP0016] DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
          proxy: listened on 8989
     livereload: listening on 35729
(node:39378) ExperimentalWarning: The fs.promises API is experimental
📦  650/650 build modules
webpack: bundle build is now finished.
Caught exception: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:140:9)
    at Object.fs.writeFile (fs.js:1258:14)
    at Recorder.self.updateRecordBody (/Users/samliu/gits/demos/intl-example/node_modules/dora-anyproxy/lib/recorder.js:103:12)
    at Recorder.self.updateRecord (/Users/samliu/gits/demos/intl-example/node_modules/dora-anyproxy/lib/recorder.js:64:14)
```

**Comment by umgsai** [comment]
遇到了一样的问题，求问怎么解决

**Comment by umgsai** [comment]
已解决，用node9或以下版本。

**Comment by PanJianNan** [comment]
除了node版本降级，还有其他什么方法吗？
